management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: kr-development

---
spring:
  config:
    activate:
      on-profile: kr-staging

---
spring:
  config:
    activate:
      on-profile: kr-production
